# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0002_listedcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedcompany',
            name='marketCapitalisation',
            field=models.FloatField(),
        ),
    ]
