# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0003_auto_20160824_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIssuedQuantitiesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityDifference', models.BigIntegerField()),
                ('marketCapitalisation', models.FloatField()),
                ('marketCapitalisationPercentage', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany')),
            ],
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketIndexHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
