# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0004_companyissuedquantitieshistory_marketindex_marketindexhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTradeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareVolume', models.BigIntegerField()),
                ('tradeVolume', models.BigIntegerField()),
                ('previouseClose', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('lastTradedPrice', models.FloatField()),
                ('priceChange', models.FloatField()),
                ('priceChangePercentage', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany')),
            ],
        ),
    ]
