# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0005_dailytradesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytradesummary',
            name='date',
            field=models.DateField(),
        ),
    ]
