# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0007_dailytradesummary_turnover'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareVolume', models.BigIntegerField()),
                ('tradeVolume', models.BigIntegerField()),
                ('priceChange', models.FloatField()),
                ('priceChangePercentage', models.FloatField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany')),
            ],
        ),
    ]
