# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0008_detailedtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MarketIndex',
        ),
        migrations.DeleteModel(
            name='MarketIndexHistory',
        ),
        migrations.AlterField(
            model_name='detailedtrade',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
