# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0010_auto_20160904_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.Investment')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='investmentType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.InvestmentType'),
            preserve_default=False,
        ),
    ]
