# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0011_auto_20160905_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityinvestment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='securityinvestment',
            name='symbol',
        ),
        migrations.AddField(
            model_name='investment',
            name='currentValue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='symbol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='SecurityInvestment',
        ),
    ]
