# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0012_auto_20160906_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
