# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0014_auto_20160911_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.Currency'),
        ),
    ]
