# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0015_investment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.Currency'),
        ),
    ]
