# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0016_auto_20160911_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany'),
        ),
    ]
