# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0017_auto_20160919_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinanceReportSumary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossTurnOver', models.FloatField()),
                ('netTurnover', models.FloatField()),
                ('profitBeforeTax', models.FloatField()),
                ('profitAfterTax', models.FloatField()),
                ('grossDividends', models.FloatField()),
                ('interestCover', models.FloatField()),
                ('dividendsCover', models.FloatField()),
                ('returnOnEquity', models.FloatField()),
                ('totalAssets', models.FloatField()),
                ('numberOfEmployees', models.IntegerField()),
                ('currentRatio', models.FloatField()),
                ('dividend', models.FloatField()),
                ('netAssets', models.FloatField()),
                ('marketValue', models.FloatField()),
                ('issueDate', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=8)),
                ('filePath', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany')),
            ],
        ),
    ]
