# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0019_companyfinancereportsumary_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='status',
        ),
    ]
