# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0020_auto_20160927_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyfinancereportsumary',
            old_name='dividend',
            new_name='dividendPerShare',
        ),
        migrations.RenameField(
            model_name='companyfinancereportsumary',
            old_name='earning',
            new_name='earningsPerShare',
        ),
        migrations.RenameField(
            model_name='companyfinancereportsumary',
            old_name='netAssets',
            new_name='netAssetsPerShare',
        ),
        migrations.RenameField(
            model_name='companyfinancereportsumary',
            old_name='netTurnover',
            new_name='revenue',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='dividendsCover',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='grossTurnOver',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='marketValue',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='numberOfEmployees',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='returnOnEquity',
        ),
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='totalShareHolderFunds',
            field=models.FloatField(default=0),
        ),
    ]
