# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0021_auto_20161004_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='dividendPerShare',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='earningsPerShare',
        ),
        migrations.RemoveField(
            model_name='companyfinancereportsumary',
            name='netAssetsPerShare',
        ),
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='numberOfShares',
            field=models.IntegerField(default=0),
        ),
    ]
