# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0025_companyfinancereportsumary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='PERatio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='earningsPerShare',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='sharePrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='companyfinancereportsumary',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
