# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0028_companyfinancereportsumary_devidendspershare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devidends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPerShare', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevidendTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dividends',
            name='investment',
        ),
        migrations.AddField(
            model_name='listedcompany',
            name='stockExchange',
            field=models.CharField(default=b'CSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailytradesummary',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Dividends',
        ),
        migrations.AddField(
            model_name='devidends',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.ListedCompany'),
        ),
        migrations.AddField(
            model_name='devidends',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.DevidendTypes'),
        ),
    ]
