# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0029_auto_20180908_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devidends',
            new_name='Dividends',
        ),

    ]
