# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0031_remove_dividends_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevidendTypes',
            new_name='DividendTypes',
        ),
    ]
