# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0033_dividends_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dividends',
            new_name='Dividend',
        ),
    ]
