# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0035_remove_dividend_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DividendTypes',
            new_name='DividendType',
        ),
    ]
