# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0036_auto_20180910_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyInvestementsManager.DividendType'),
            preserve_default=False,
        ),
    ]
