# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0037_dividend_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividend',
            old_name='date',
            new_name='announced_date',
        ),
        migrations.AddField(
            model_name='dividend',
            name='entitled_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
