# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0038_auto_20180910_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
