# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0039_dividend_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='announced_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='entitled_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
