# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0040_auto_20180929_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='announced_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='entitled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
