# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-20 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInvestementsManager', '0042_reporttables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttables',
            name='tables',
            field=models.TextField(),
        ),
    ]
